### ISSUE TITLE
Add support for libvirt

### ISSUE THREAD

**Issue by jdef** [dcos/dcos-vagrant#22]
I much prefer libvirt vs. virtualbox. @vishnu2kmohan don't you have a branch for this kicking around somewhere?

**Comment by karlkfi** [comment]
Moved to https://dcosjira.atlassian.net/browse/DCOS-27

**Comment by as0bu** [comment]
I know that this is closed, but @jdef there is a plugin for vagrant called 'vagrant-mutator' that might be of interest to you. This will convert virtualbox vagrant boxes to libvirt for you. You may also need to comment out part of the Vagrantfile that specifies the URL and Version forcing vagrant to use the box converted by the mutator plugin.
