### ISSUE TITLE
Update Docker in dcos-vagrant

### ISSUE THREAD

**Issue by alberts** [dcos/dcos-vagrant#39]
For dcos-docker, we'd like Docker 1.10.3 or later in mesosphere/dcos-centos-virtualbox so that we can use

STOPSIGNAL SIGRTMIN+3

in Dockerfiles.

**Comment by robbrockbank** [comment]
We'd like this too, so that we can use Docker user definable networks.

**Comment by karlkfi** [comment]
Needs a dcos-vagrant-box update, which has a ticket already: https://github.com/dcos/dcos-vagrant-box/issues/3

**Comment by karlkfi** [comment]
dcos-vagrant-box 0.5.0 has docker 1.11
