### ISSUE TITLE
dcos install kafka and others give me errors

### ISSUE THREAD

**Issue by giux78** [dcos/dcos-vagrant#42]
The installation of dcos-vagrant on Ubuntu 14.04 with 32gb ram works perfectly. But when I try to install kafka or cassandra i get this erros for stderror

I0420 07:24:57.845353  6403 logging.cpp:188] INFO level logging started!
I0420 07:24:57.845574  6403 fetcher.cpp:424] Fetcher Info: {"cache_directory":"\/tmp\/mesos\/fetch\/slaves\/5100a94b-c078-4915-abd9-14e58481d016-S1\/root","items":[{"action":"BYPASS_CACHE","uri":{"cache":false,"executable":false,"extract":true,"value":"https:\/\/s3.amazonaws.com\/downloads.mesosphere.io\/kafka\/assets\/0.2.5-0.9.0.1\/jre-8u72-linux-x64.tar.gz"}},{"action":"BYPASS_CACHE","uri":{"cache":false,"executable":false,"extract":true,"value":"https:\/\/s3.amazonaws.com\/downloads.mesosphere.io\/kafka\/assets\/0.2.5-0.9.0.1\/scheduler.zip"}},{"action":"BYPASS_CACHE","uri":{"cache":false,"executable":false,"extract":true,"value":"https:\/\/s3.amazonaws.com\/downloads.mesosphere.io\/kafka\/assets\/0.2.5-0.9.0.1\/kafka_2.10-0.9.0.1.tgz"}}],"sandbox_directory":"\/var\/lib\/mesos\/slave\/slaves\/5100a94b-c078-4915-abd9-14e58481d016-S1\/frameworks\/5100a94b-c078-4915-abd9-14e58481d016-0000\/executors\/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e\/runs\/b08ff86a-c72e-4bb7-a68d-367a09b22b17","user":"root"}
I0420 07:24:57.846779  6403 fetcher.cpp:379] Fetching URI 'https://s3.amazonaws.com/downloads.mesosphere.io/kafka/assets/0.2.5-0.9.0.1/jre-8u72-linux-x64.tar.gz'
I0420 07:24:57.846786  6403 fetcher.cpp:250] Fetching directly into the sandbox directory
I0420 07:24:57.846797  6403 fetcher.cpp:187] Fetching URI 'https://s3.amazonaws.com/downloads.mesosphere.io/kafka/assets/0.2.5-0.9.0.1/jre-8u72-linux-x64.tar.gz'
I0420 07:24:57.846807  6403 fetcher.cpp:134] Downloading resource from 'https://s3.amazonaws.com/downloads.mesosphere.io/kafka/assets/0.2.5-0.9.0.1/jre-8u72-linux-x64.tar.gz' to '/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17/jre-8u72-linux-x64.tar.gz'
I0420 07:27:18.438141  6403 fetcher.cpp:84] Extracting with command: tar -C '/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17' -xf '/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17/jre-8u72-linux-x64.tar.gz'
I0420 07:27:19.806716  6403 fetcher.cpp:92] Extracted '/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17/jre-8u72-linux-x64.tar.gz' into '/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17'
I0420 07:27:19.806740  6403 fetcher.cpp:456] Fetched 'https://s3.amazonaws.com/downloads.mesosphere.io/kafka/assets/0.2.5-0.9.0.1/jre-8u72-linux-x64.tar.gz' to '/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17/jre-8u72-linux-x64.tar.gz'
I0420 07:27:19.806756  6403 fetcher.cpp:379] Fetching URI 'https://s3.amazonaws.com/downloads.mesosphere.io/kafka/assets/0.2.5-0.9.0.1/scheduler.zip'
I0420 07:27:19.806758  6403 fetcher.cpp:250] Fetching directly into the sandbox directory
I0420 07:27:19.806767  6403 fetcher.cpp:187] Fetching URI 'https://s3.amazonaws.com/downloads.mesosphere.io/kafka/assets/0.2.5-0.9.0.1/scheduler.zip'
I0420 07:27:19.806773  6403 fetcher.cpp:134] Downloading resource from 'https://s3.amazonaws.com/downloads.mesosphere.io/kafka/assets/0.2.5-0.9.0.1/scheduler.zip' to '/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17/scheduler.zip'
I0420 07:27:24.164655  6403 fetcher.cpp:84] Extracting with command: unzip -d '/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17' '/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17/scheduler.zip'
I0420 07:27:24.338912  6403 fetcher.cpp:92] Extracted '/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17/scheduler.zip' into '/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17'
I0420 07:27:24.338939  6403 fetcher.cpp:456] Fetched 'https://s3.amazonaws.com/downloads.mesosphere.io/kafka/assets/0.2.5-0.9.0.1/scheduler.zip' to '/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17/scheduler.zip'
I0420 07:27:24.338945  6403 fetcher.cpp:379] Fetching URI 'https://s3.amazonaws.com/downloads.mesosphere.io/kafka/assets/0.2.5-0.9.0.1/kafka_2.10-0.9.0.1.tgz'
I0420 07:27:24.338949  6403 fetcher.cpp:250] Fetching directly into the sandbox directory
I0420 07:27:24.338976  6403 fetcher.cpp:187] Fetching URI 'https://s3.amazonaws.com/downloads.mesosphere.io/kafka/assets/0.2.5-0.9.0.1/kafka_2.10-0.9.0.1.tgz'
I0420 07:27:24.338984  6403 fetcher.cpp:134] Downloading resource from 'https://s3.amazonaws.com/downloads.mesosphere.io/kafka/assets/0.2.5-0.9.0.1/kafka_2.10-0.9.0.1.tgz' to '/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17/kafka_2.10-0.9.0.1.tgz'
I0420 07:27:28.695291  6403 fetcher.cpp:84] Extracting with command: tar -C '/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17' -xf '/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17/kafka_2.10-0.9.0.1.tgz'
I0420 07:27:28.975829  6403 fetcher.cpp:92] Extracted '/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17/kafka_2.10-0.9.0.1.tgz' into '/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17'
I0420 07:27:28.975867  6403 fetcher.cpp:456] Fetched 'https://s3.amazonaws.com/downloads.mesosphere.io/kafka/assets/0.2.5-0.9.0.1/kafka_2.10-0.9.0.1.tgz' to '/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17/kafka_2.10-0.9.0.1.tgz'
I0420 07:27:29.130259  6400 exec.cpp:143] Version: 0.28.1
I0420 07:27:29.132279  6757 exec.cpp:217] Executor registered on slave 5100a94b-c078-4915-abd9-14e58481d016-S1
log4j:WARN No appenders could be found for logger (org.jboss.logging).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Under replicated partition count = 0
I0420 07:27:32.675235  6850 sched.cpp:222] Version: 0.28.1
2016-04-20 07:27:32,675:6766(0x7f6c18e47700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2016-04-20 07:27:32,675:6766(0x7f6c18e47700):ZOO_INFO@log_env@716: Client environment:host.name=a1.dcos
2016-04-20 07:27:32,675:6766(0x7f6c18e47700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2016-04-20 07:27:32,675:6766(0x7f6c18e47700):ZOO_INFO@log_env@724: Client environment:os.arch=3.10.0-327.10.1.el7.x86_64
2016-04-20 07:27:32,675:6766(0x7f6c18e47700):ZOO_INFO@log_env@725: Client environment:os.version=#1 SMP Tue Feb 16 17:03:50 UTC 2016
2016-04-20 07:27:32,675:6766(0x7f6c18e47700):ZOO_INFO@log_env@733: Client environment:user.name=(null)
2016-04-20 07:27:32,676:6766(0x7f6c18e47700):ZOO_INFO@log_env@741: Client environment:user.home=/root
2016-04-20 07:27:32,676:6766(0x7f6c18e47700):ZOO_INFO@log_env@753: Client environment:user.dir=/var/lib/mesos/slave/slaves/5100a94b-c078-4915-abd9-14e58481d016-S1/frameworks/5100a94b-c078-4915-abd9-14e58481d016-0000/executors/kafka.a8a65c5b-0703-11e6-8b8b-ce258879023e/runs/b08ff86a-c72e-4bb7-a68d-367a09b22b17
2016-04-20 07:27:32,676:6766(0x7f6c18e47700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=master.mesos:2181 sessionTimeout=10000 watcher=0x7f6c1b42a030 sessionId=0 sessionPasswd=<null> context=0x7f6c2c001700 flags=0
2016-04-20 07:27:32,682:6766(0x7f6c1463e700):ZOO_INFO@check_events@1703: initiated connection to server [192.168.65.90:2181]
2016-04-20 07:27:32,685:6766(0x7f6c1463e700):ZOO_INFO@check_events@1750: session establishment complete on server [192.168.65.90:2181], sessionId=0x1543393f7290023, negotiated timeout=10000
I0420 07:27:32.685724  6864 group.cpp:349] Group process (group(1)@192.168.65.111:43209) connected to ZooKeeper
I0420 07:27:32.685784  6864 group.cpp:831] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
I0420 07:27:32.685793  6864 group.cpp:427] Trying to create path '/mesos' in ZooKeeper
I0420 07:27:32.687435  6864 detector.cpp:152] Detected a new leader: (id='1')
I0420 07:27:32.687543  6864 group.cpp:700] Trying to get '/mesos/json.info_0000000001' in ZooKeeper
I0420 07:27:32.688284  6864 detector.cpp:479] A new leading master (UPID=master@192.168.65.101:5050) is detected
I0420 07:27:32.688349  6864 sched.cpp:326] New master detected at master@192.168.65.101:5050
I0420 07:27:32.688467  6864 sched.cpp:336] No credentials provided. Attempting to register without authentication
I0420 07:27:32.689965  6864 sched.cpp:703] Framework registered with 5100a94b-c078-4915-abd9-14e58481d016-0002
2016-04-20 07:27:42,708:6766(0x7f6c1463e700):ZOO_WARN@zookeeper_interest@1557: Exceeded deadline by 12ms
2016-04-20 07:28:02,740:6766(0x7f6c1463e700):ZOO_WARN@zookeeper_interest@1557: Exceeded deadline by 11ms
2016-04-20 07:28:06,114:6766(0x7f6c1463e700):ZOO_WARN@zookeeper_interest@1557: Exceeded deadline by 39ms
Under replicated partition count = 0
2016-04-20 07:28:42,841:6766(0x7f6c1463e700):ZOO_WARN@zookeeper_interest@1557: Exceeded deadline by 14ms

**Comment by karlkfi** [comment]
Most of the services have default configurations for production use that don't actually fit on dcos-vagrant (usually memory constraints). Some can scale down, some can't. 

Minimal config recommendations for the new Infinity frameworks (incl Kafka and Cassandra) are still TBD. YMMV.

**Comment by karlkfi** [comment]
@giux78: Can you create bug reports in the new DCOS Jira under the cassandra and kafka components?
https://dcosjira.atlassian.net/projects/DCOS?selectedItem=com.atlassian.jira.jira-projects-plugin:components-page

The teams that own those services are in charge of getting them working on dcos-vagrant and triaging related issues. If they have trouble they'll get in touch with me.

If you make the tickets then you can more easily follow their progress.

**Comment by karlkfi** [comment]
Once you make tickets, link them here so other people who see this issue can find them.

**Comment by giux78** [comment]
Thanks here the link to the issue on jira.
