### ISSUE TITLE
Getting error while bringing up the machines

### ISSUE THREAD

**Issue by vivekkothari** [dcos/dcos-vagrant#44]
C02P30YXG3QC:dcos-vagrant vivek.kothari$ vagrant up m1 a1 p1 boot
Bringing machine 'm1' up with 'virtualbox' provider...
Bringing machine 'a1' up with 'virtualbox' provider...
Bringing machine 'p1' up with 'virtualbox' provider...
Bringing machine 'boot' up with 'virtualbox' provider...
==> m1: Checking if box 'mesosphere/dcos-centos-virtualbox' is up to date...
==> m1: VirtualBox VM is already running.
==> a1: Checking if box 'mesosphere/dcos-centos-virtualbox' is up to date...
==> a1: VirtualBox VM is already running.
==> p1: Checking if box 'mesosphere/dcos-centos-virtualbox' is up to date...
==> p1: VirtualBox VM is already running.
There are errors in the configuration of this machine. Please fix
the following errors and try again:

shell provisioner:
* The following settings shouldn't exist: env

**Comment by karlkfi** [comment]
Upgrade vagrant: https://github.com/dcos/dcos-vagrant/blob/master/docs/troubleshooting.md#provision-environment-support
