### ISSUE TITLE
sudoers file is broken 

### ISSUE THREAD

**Issue by huiwenhan** [dcos/dcos-vagrant#48]
Hi ,

My sudoers file is broken ,how can I repair the system ?

Does root account has default password ?

Best Regards,

huiwenhan

**Comment by karlkfi** [comment]
You're going to have to be a little more descriptive... What sudoers file? Which system? Root account on what machine?

The account on the base os image is vagrant/vagrant. But you can get into it with just `vagrant ssh <machine>` using the configured SSH key.

**Comment by karlkfi** [comment]
Closing from lack of feedback.
