### ISSUE TITLE
VBoxManage hostonlyif create on windows

### ISSUE THREAD

**Issue by webmutation** [dcos/dcos-vagrant#51]
Virtualbox is platform specific when creating the networks.

On windows "VBoxManage hostonlyif create" will create an interface with the following name "VirtualBox Host-Only Ethernet Adapter" not "vboxnet0" this will result that running "VBoxManage hostonlyif ipconfig vboxnet0 --ip 192.168.65.1" to fail.

The workaround is simple
 VBoxManage hostonlyif ipconfig "VirtualBox Host-Only Ethernet Adapter" --ip 192.168.65.1

**Comment by karlkfi** [comment]
Does this work for you?

```
VBoxManage list hostonlyifs | grep vboxnet0 -q || VBoxManage hostonlyif create | grep "successfully created" | sed "s/Interface '\(.*\)' was successfully created/'\1'/" | xargs VBoxManage hostonlyif ipconfig --ip 192.168.65.1
```

I'm looking for a solution that will work cross platform so I don't have to have different instructions for different platforms.

If it works I could make a bash script to do it for you, instead of having people copy and paste.

**Comment by karlkfi** [comment]
oh, nope. that's always gonna create a new hostonlyif on windows because the first conditional never succeeds...

**Comment by karlkfi** [comment]
This should work:

```
VBoxManage list hostonlyifs | grep 'IPAddress:.*192.168.65.1' -q || VBoxManage hostonlyif create | grep "successfully created" | sed "s/Interface '\(.*\)' was successfully created/'\1'/" | xargs VBoxManage hostonlyif ipconfig --ip 192.168.65.1
```

**Comment by karlkfi** [comment]
ya'know... I can just make ruby do the host network setup for you... I'll have it make a new one if one doesn't exist that's configured to use the desired IP range. One less manual step for users to worry about.

https://github.com/dcos/dcos-vagrant/commit/29a88d764258ab9b6080f05eadb18f8e616ed71b

**Comment by webmutation** [comment]
Hi karlikfi,
Well that is even better :)
 
I'm still having some issue running the VMs in windows. apparently the authentication

I changed the 
**%WINDIR%\System32\drivers\etc\hosts**

**export DCOS_CONFIG_PATH=etc/config-1.7.yaml **
to 
**set DCOS_CONFIG_PATH=C:\DEV\dcos\dcos-vagrant\config-1.7.yaml**

But when I Vagrant Up
**vagrant up m1 a1 a2 a3 a4 p1 boot**
 I run into 
>     boot: SSH address: 127.0.0.1:2206
>     boot: SSH username: vagrant
>     boot: SSH auth method: private key
>     boot: Warning: Remote connection disconnect. Retrying...
>     boot: Warning: Remote connection disconnect. Retrying...
>     boot: Warning: Remote connection disconnect. Retrying...
>     boot:
>     boot: Vagrant insecure key detected. Vagrant will automatically replace
>     boot: this with a newly generated keypair for better security.
> 	Timed out while waiting for the machine to boot. This means that
> Vagrant was unable to communicate with the guest machine within
> the configured ("config.vm.boot_timeout" value) time period.
> 
> If you look above, you should be able to see the error(s) that
> Vagrant had when attempting to connect to the machine. These errors
> are usually good hints as to what may be wrong.
> 
> If you're using a custom box, make sure that networking is properly
> working and you're able to connect to the machine. It is a common
> problem that networking isn't setup properly in these boxes.
> Verify that authentication configurations are also setup properly,
> as well.
> 
> If the box appears to be booting properly, you may want to increase
> the timeout ("config.vm.boot_timeout") value.

**Comment by karlkfi** [comment]
The timeout issue is documented here: https://github.com/dcos/dcos-vagrant/issues/40
It's so far unsolved but there are a few suggestions there to try. 
Also, try not to use closed threads for new topics in the future.

**Comment by karlkfi** [comment]
Also: DCOS_CONFIG_PATH needs to be relative to the repo dir, not absolute.
