### ISSUE TITLE
Login screen forces me to use Github/Google/Microsoft to login, no place to manually login

### ISSUE THREAD

**Issue by gnomeontherun** [dcos/dcos-vagrant#53]
I provisioned a small environment and can reach m1.dcos. However, I get the login screen without the ability to login with a user/pass.

How can I proceed? Do I need to set some configuration that will enable me to use the default admin login? I tried to login with Github but get an error about not being connected to the internet.

![screen shot 2016-05-02 at 11 37 44 am](https://cloud.githubusercontent.com/assets/79500/14960465/64808462-105a-11e6-9b39-7d5051ea0322.png)

![screen shot 2016-05-02 at 11 40 32 am](https://cloud.githubusercontent.com/assets/79500/14960531/b4ae4d66-105a-11e6-92fa-ca49552a4d52.png)

**Comment by karlkfi** [comment]
Currently, internet is required for DC/OS to be fully functional, primarily for Oauth login and package management using Mesosphere Universe.

Local and LDAP auth options are features of Mesosphere Enterprise DC/OS: https://mesosphere.com/enterprise/

Auth can be disabled altogether, tho, by using the opt-out procedure before installation: https://dcos.io/docs/1.7/administration/opt-out/
