### ISSUE TITLE
Command not found errors

### ISSUE THREAD

**Issue by imesh** [dcos/dcos-vagrant#54]
I see the below errors at the end of the vagrant setup:

==> boot: Generating IP Detection Script: ~/dcos/genconf/ip-detect
==> boot: sudo: cat << EOF > ~/dcos/genconf/ip-detect
==> boot:       #!/usr/bin/env bash
==> boot:       set -o errexit
==> boot:       set -o nounset
==> boot:       set -o pipefail
==> boot:       echo \$(/usr/sbin/ip route show to match 192.168.65.90 | grep -Eo '[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}' | tail -1)
==> boot:
==> boot:       EOF
==> boot: Importing Private SSH Key: ~/dcos/genconf/ssh_key
==> boot: sudo: cp /vagrant/.vagrant/dcos/private_key_vagrant ~/dcos/genconf/ssh_key
==> boot: Generating DC/OS Installer Files: ~/dcos/genconf/serve/
==> boot: sudo: cd ~/dcos && bash ~/dcos/dcos_generate_config.sh --genconf && cp -rpv ~/dcos/genconf/serve/* /var/tmp/dcos/
==> boot:       /root/dcos/dcos_generate_config.sh: line 1: ---: command not found
==> boot:       /root/dcos/dcos_generate_config.sh: line 2: cluster_name:: command not found
==> boot:       /root/dcos/dcos_generate_config.sh: line 3: bootstrap_url:: command not found
==> boot:       /root/dcos/dcos_generate_config.sh: line 4: exhibitor_storage_backend:: command not found
==> boot:       /root/dcos/dcos_generate_config.sh: line 5: exhibitor_zk_hosts:: command not found
==> boot:       /root/dcos/dcos_generate_config.sh: line 6: exhibitor_zk_path:: command not found
==> boot:       /root/dcos/dcos_generate_config.sh: line 7: master_discovery:: command not found
==> boot:       /root/dcos/dcos_generate_config.sh: line 8: master_list:: command not found
==> boot:       /root/dcos/dcos_generate_config.sh: line 9: -: command not found
==> boot:       /root/dcos/dcos_generate_config.sh: line 10: resolvers:: command not found
==> boot:       /root/dcos/dcos_generate_config.sh: line 11: -: command not found
==> boot:       /root/dcos/dcos_generate_config.sh: line 12: superuser_username:: command not found
==> boot:       /root/dcos/dcos_generate_config.sh: line 13: superuser_password_hash:: command not found
==> boot:       /root/dcos/dcos_generate_config.sh: line 14: ssh_port:: command not found
==> boot:       /root/dcos/dcos_generate_config.sh: line 15: ssh_user:: command not found
==> boot:       /root/dcos/dcos_generate_config.sh: line 16: agent_list:: command not found
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cd ~/dcos && bash ~/dcos/dcos_generate_config.sh --genconf && cp -rpv ~/dcos/genconf/serve/* /var/tmp/dcos/

Stdout from the command:
Stderr from the command:

/root/dcos/dcos_generate_config.sh: line 1: ---: command not found
/root/dcos/dcos_generate_config.sh: line 2: cluster_name:: command not found
/root/dcos/dcos_generate_config.sh: line 3: bootstrap_url:: command not found
/root/dcos/dcos_generate_config.sh: line 4: exhibitor_storage_backend:: command not found
/root/dcos/dcos_generate_config.sh: line 5: exhibitor_zk_hosts:: command not found
/root/dcos/dcos_generate_config.sh: line 6: exhibitor_zk_path:: command not found
/root/dcos/dcos_generate_config.sh: line 7: master_discovery:: command not found
/root/dcos/dcos_generate_config.sh: line 8: master_list:: command not found
/root/dcos/dcos_generate_config.sh: line 9: -: command not found
/root/dcos/dcos_generate_config.sh: line 10: resolvers:: command not found
/root/dcos/dcos_generate_config.sh: line 11: -: command not found
/root/dcos/dcos_generate_config.sh: line 12: superuser_username:: command not found
/root/dcos/dcos_generate_config.sh: line 13: superuser_password_hash:: command not found
/root/dcos/dcos_generate_config.sh: line 14: ssh_port:: command not found
/root/dcos/dcos_generate_config.sh: line 15: ssh_user:: command not found
/root/dcos/dcos_generate_config.sh: line 16: agent_list:: command not found

**Comment by karlkfi** [comment]
What platform/os/virtualbox/vagrant?
What env variable configuration were you using?

**Comment by imesh** [comment]
@karlkfi I'm sorry I couldn't mentioned those, please find them below:

OS: OSX=10.11.2
VirtualBox=5.0.16
Vagrant=1.8.1
DCOS Vagrant=v0.6.0
DCOS_GENERATE_CONFIG_PATH=dcos_generate_config.sh
DCOS_GENERATE_CONFIG_PATH=etc/config-1.7.yaml
Vagrant up Arguments=vagrant up m1 a1 p1 boot

**Comment by imesh** [comment]
BTW may I know what dcos_generate_config.sh does? As I can see it's around 550 mb and has binary data. Thanks!

**Comment by karlkfi** [comment]
`dcos_generate_config.sh` is the DC/OS installer. It's a shell script that includes a binary encoded docker image.

**Comment by imesh** [comment]
@karlkfi Thanks! What would be the reason for including a Docker image in a shell script? Anyway I tried this Vagrant setup many times by changing to different versions but still could not get it working.

**Comment by karlkfi** [comment]
It allows for installing without an Internet connection, bundling all the OS and lib dependencies so that the user doesn't need to install them all manually (slow & tedious) or use flakey remote package repositories.

**Comment by karlkfi** [comment]
Have you tried redownloading dcos_generate_config.sh? The download may be corrupt. I'm not sure if there are shas to easily verify integrity...

**Comment by imesh** [comment]
Thanks @karlkfi! Today I took a pull from the master branch and re-executed the vagrant with the following parameters and guess what, it worked! :-) Thanks for you help!

export DCOS_GENERATE_CONFIG_PATH=dcos_generate_config.sh
export DCOS_CONFIG_PATH=etc/config-1.7.yaml
vagrant up m1 a1 a2 p1 boot
