### ISSUE TITLE
Attempting to configure DCOS_PRIVATE_REGISTRY fails

### ISSUE THREAD

**Issue by cneth** [dcos/dcos-vagrant#55]
OS: OSX=10.11.4
VirtualBox=5.0.16
Vagrant=1.8.1
DCOS_CONFIG_PATH=etc/config-1.6.yaml
DCOS_PRIVATE_REGISTRY=true
Vagrant up Arguments=vagrant up m1 a1 p1 boot

I am attempting to install the DCOS 1.6 Enterprise Edition bits.   I was successful in doing so if I used a vanilla config.     After that success, I destroyed the config and set the DCOS_PRIVATE_REGISTRY env variable to true and tried again.   That resulted in the following failure:

==> m1: >>> Registering private docker registry: boot.dcos:5000
==> m1: sed: can't read /etc/sysconfig/docker: No such file or directory

It looks like the provision/bin/insecure-registry.sh script makes some incorrect assumptions about how Docker is installed on the base box....   

Craig

USMA03MML11008:dcos-vagrant v625018$ export DCOS_PRIVATE_REGISTRY=true
TUSMA03MML11008:dcos-vagrant v625018$ set | grep DCOS
DCOS_CONFIG_PATH=etc/config-1.6.yaml
DCOS_PRIVATE_REGISTRY=true
_=DCOS_PRIVATE_REGISTRY
TUSMA03MML11008:dcos-vagrant v625018$ vagrant up m1 a1 p1 boot
Bringing machine 'm1' up with 'virtualbox' provider...
Bringing machine 'a1' up with 'virtualbox' provider...
Bringing machine 'p1' up with 'virtualbox' provider...
Bringing machine 'boot' up with 'virtualbox' provider...
==> m1: Importing base box 'mesosphere/dcos-centos-virtualbox'...
==> m1: Matching MAC address for NAT networking...
==> m1: Checking if box 'mesosphere/dcos-centos-virtualbox' is up to date...
==> m1: Setting the name of the VM: m1.dcos
==> m1: Clearing any previously set network interfaces...
==> m1: Preparing network interfaces based on configuration...
    m1: Adapter 1: nat
    m1: Adapter 2: hostonly
==> m1: Forwarding ports...
    m1: 22 (guest) => 2222 (host) (adapter 1)
==> m1: Running 'pre-boot' VM customizations...
==> m1: Booting VM...
==> m1: Waiting for machine to boot. This may take a few minutes...
    m1: SSH address: 127.0.0.1:2222
    m1: SSH username: vagrant
    m1: SSH auth method: private key
    m1: Warning: Remote connection disconnect. Retrying...
    m1: Warning: Remote connection disconnect. Retrying...
    m1: Warning: Remote connection disconnect. Retrying...
    m1: 
    m1: Vagrant insecure key detected. Vagrant will automatically replace
    m1: this with a newly generated keypair for better security.
    m1: 
    m1: Inserting generated public key within guest...
    m1: Removing insecure key from the guest if it's present...
    m1: Key inserted! Disconnecting and reconnecting using new SSH key...
==> m1: Machine booted and ready!
GuestAdditions versions on your host (5.0.16) and guest (5.0.8) do not match.
Loaded plugins: fastestmirror
Determining fastest mirrors
 * base: centos-distro.1gservers.com
 * extras: mirror.stjschools.org
 * updates: mirror.confluxtech.com
Package kernel-devel-3.10.0-327.13.1.el7.x86_64 already installed and latest version
Package gcc-4.8.5-4.el7.x86_64 already installed and latest version
Package 1:make-3.82-21.el7.x86_64 already installed and latest version
Package 4:perl-5.16.3-286.el7.x86_64 already installed and latest version
Package bzip2-1.0.6-13.el7.x86_64 already installed and latest version
Nothing to do
Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
mount: /dev/loop0 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 5.0.16 - guest version is 5.0.8
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.0.16 Guest Additions for Linux............
VirtualBox Guest Additions installer
Removing installed version 5.0.8 of VirtualBox Guest Additions...
Removing existing VirtualBox non-DKMS kernel modules[  OK  ]
Copying additional installer modules ...
Installing additional modules ...
Removing existing VirtualBox non-DKMS kernel modules[  OK  ]
Building the VirtualBox Guest Additions kernel modules
Building the main Guest Additions module[  OK  ]
Building the shared folder support module[  OK  ]
Building the OpenGL support module[  OK  ]
Doing non-kernel setup of the Guest Additions[  OK  ]
You should restart your guest to make sure the new modules are actually used

Installing the Window System drivers
Could not find the X.Org or XFree86 Window System, skipping.
An error occurred during installation of VirtualBox Guest Additions 5.0.16. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
==> m1: Checking for guest additions in VM...
==> m1: Setting hostname...
==> m1: Configuring and enabling network interfaces...
==> m1: Mounting shared folders...
    m1: /vagrant => /Users/v625018/work/dcos-vb/dcos-vagrant
==> m1: Updating /etc/hosts file on active guest machines...
==> m1: Updating /etc/hosts file on host machine (password may be required)...
Password:
==> m1: Running provisioner: dcos_ssh...
    host: Found existing keys
==> m1: Inserting generated public key within guest...
==> m1: Configuring vagrant to connect using generated private key...
==> m1: Removing insecure key from the guest, if it's present...
==> m1: Running provisioner: shell...
    m1: Running: script: Certificate Authorities
==> m1: >>> Installing Certificate Authorities
==> m1: Running provisioner: shell...
    m1: Running: script: Private Docker Registry
==> m1: >>> Registering private docker registry: boot.dcos:5000
==> m1: sed: can't read /etc/sysconfig/docker: No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by karlkfi** [comment]
Ahh, yeah. I haven't tested that with the new docker 1.11 install. It should work if you use the previous os image with docker 1.8. But it'll need to be fixed on master.

**Comment by cneth** [comment]
They've made it somewhat painful, unfortunately.    The main docker.service unit file does not include the DOCKER_OPTS environment variable, so you can't just do a simple drop-in with DOCKER_OPTS setting. Instead I guess the recommendation is to override the ExecStart specification in the drop-in (or hack up the docker.service unit).

**Comment by karlkfi** [comment]
I've already done some rather hacky ExecStart mutation in the box building: https://github.com/dcos/dcos-vagrant-box/blob/master/bin/docker.sh#L27

The 1.11 docker.service file is a lot less complex than the 1.8 one. It doesn't allow configuration by multiple env vars like it used too.

**Comment by karlkfi** [comment]
Fixed: https://github.com/dcos/dcos-vagrant/commit/129b3eb08818c5915bf0ebe9c36aa280095dcfb6
