### ISSUE TITLE
DNS not set on master nodes

### ISSUE THREAD

**Issue by gianluca-sabena** [dcos/dcos-vagrant#59]
I'm using mac os x, Version 5.0.20 r106931, Vagrant 1.8.1
- dcos-vagrant 0.7.0
- I can ping and access internt from boot node
- DNS is not set up on master 

As a consequence I can't install packages from Universe repository

**Comment by karlkfi** [comment]
What do you mean by "DNS not set"? What are the symptoms and how did you diagnose?

**Comment by piwi3910** [comment]
same as issue #58

**Comment by gianluca-sabena** [comment]
It is working.
Sorry to report, default dns (8.8.8.8) was blocked on my firewall.
