### ISSUE TITLE
push to private registry from jenkins job?

### ISSUE THREAD

**Issue by tony-kerz** [dcos/dcos-vagrant#60]
trying to run a jenkins job which:

1. creates an image
1. pushes it to a private/insecure repo
1. posts to marathon rest api to run said image (marathon json will refer to image at private/insecure repo)

my first pass called out to `boot.dcos` as the insecure reg host:
```
+ docker push boot.dcos:5000/fhir-client:7308a9b
The push refers to a repository [boot.dcos:5000/fhir-client]
unable to ping registry endpoint https://boot.dcos:5000/v0/
v2 ping attempt failed with error: Get https://boot.dcos:5000/v2/: dial tcp: lookup boot.dcos on 198.51.100.1:53: no such host
 v1 ping attempt failed with error: Get https://boot.dcos:5000/v1/_ping: dial tcp: lookup boot.dcos on 198.51.100.1:53: no such host
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```
but adding `ping boot.dcos -c 1` to the jenkins job showed that `boot.dcos` wasn't visible in that context,
so i tried the ip `192.168.65.50` which was visible to jenkins, but:
```
+ docker push 192.168.65.50:5000/fhir-client:7308a9b
The push refers to a repository [192.168.65.50:5000/fhir-client]
unable to ping registry endpoint https://192.168.65.50:5000/v0/
v2 ping attempt failed with error: Get https://192.168.65.50:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://192.168.65.50:5000/v1/_ping: tls: oversized record received with length 20527
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```
i have done this in the past, but via volume mounting docker socket technique (`/var/run/docker.sock`),
i guess this has something to do with the d-in-d technique in play in the jenkins/jenkins-mesos package setup,
would it need to be configured to allow an insecure registry or something?

any guidance appreciated...

**Comment by karlkfi** [comment]
Jenkins on DC/OS runs its builds in containers. Those containers need to inherit the agent node's `/etc/hosts` in order to properly resolve `boot.dcos`. This should happen by default. You might try `cat /etc/hosts` on the node and inside the container to see if it's being updated correctly.

**Comment by karlkfi** [comment]
Another thing: Because Jenkins's build containers have their own docker daemon inside them (docker-in-docker), those daemons need to be configured to allow `boot.dcos:5000` as an insecure repo. You can see how do do that here: https://github.com/dcos/dcos-vagrant/blob/master/provision/bin/insecure-registry.sh

You'll either need to use a new jenkins container that includes that change or perform the change in each build that wants to use the private registry.

**Comment by karlkfi** [comment]
In production, you would just give the private repo a real SSL key so you don't have to modify the docker daemon.

**Comment by diversemix** [comment]
I have the same issue: I specify a "http://...." in the "Docker registry URL" field and in the build console output it is magically changed to "https://...."

**Comment by diversemix** [comment]
Also the URL contained "v2" which also magically changes to "v1"

**Comment by karlkfi** [comment]
The private registry is sort of a value-add thing with dcos-vagrant, not a feature of DC/OS or Jenkins/Velocity. So it's not particularly well tested and not recommended for production. So anything I recommend is really just gonna be a workaround.

That said, if you want to hack your Velocity build container, you can build your own: https://docs.mesosphere.com/usage/services/velocity/creating-custom-build-agents/ 
You can trivially build a new docker image that extends https://github.com/mesosphere/jenkins-dind-agent and reconfigured the container.

@diversemix: can you be more specific? what url gets changed to what?

**Comment by karlkfi** [comment]
I've made a JIRA to track the self-signed cert option (https://dcosjira.atlassian.net/browse/DCOS-128), but even with that you need some way to mount the cert into the jenkins build container, which I'm not sure how to do.

On top of that, you would need to add boot.dcos to the `/etc/hosts` inside the Jenkins build container, which would require passing `--add-host="boot.dcos:192.168.65.50"` to the docker run command, but I'm not sure if Velocity makes that configurable.

**Comment by karlkfi** [comment]
Normally, in production, you'd have your private registry with a proper SSL cert and a real DNS server to resolve it's FQDN. I've contemplated making a DNS for dcos-vagrant, but it's not on the TODO list yet.

**Comment by karlkfi** [comment]
Jenkins Docker configuration is a little hard to get to:
Jenkins > Manage Jenkins > Configure System > Cloud > Advanced > Advanced

<img width="540" alt="jenkins docker config" src="https://cloud.githubusercontent.com/assets/3980984/15478133/5a9f9c0c-20cd-11e6-8fe3-cd4880ab8bf8.png">

The Volumes and Parameters should be configurable:

<img width="656" alt="jenkins docker volumes and parameters" src="https://cloud.githubusercontent.com/assets/3980984/15478161/99590bea-20cd-11e6-9642-130ab2b91baf.png">

Once an SSL certificate is generated, configured on the docker registry, and the CA cert is added to each node (https://dcosjira.atlassian.net/browse/DCOS-128), you can mount the CA cert into each Jenkins container by adding a volume for `/etc/docker/certs.d/boot.dcos:5000/ca.crt`.

Then, to allow for `boot.dcos` host mapping, you can add `--add-host="boot.dcos:192.168.65.50"` as a docker parameter.

**Comment by karlkfi** [comment]
Moving this to JIRA so I can close github issues: https://dcosjira.atlassian.net/browse/VAGRANT-21
Feel free to log in and watch the ticket to get notifications of updates.
