### ISSUE TITLE
Mesos slave custom configuration

### ISSUE THREAD

**Issue by gianluca-sabena** [dcos/dcos-vagrant#61]
How can I add a custom configuration to a slave during vagrant configuration?

**Comment by karlkfi** [comment]
dcos-vagrant is not currently programmed to allow that to be configured easily, but you could hypothetically add a provisioner script to do so. You'd need to modify the systemd unit file to update the args or env vars.

**Comment by karlkfi** [comment]
I'm not planning to make it easier to hack mesos configs with dcos-vagrant, but if you have a proposal, I'd be happy to consider a PR to do so.
