### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by fabriziopandini** [dcos/dcos-vagrant#62]
Link to "DC/OS Usage docs" in https://github.com/dcos/dcos-vagrant/README.md leads to a 404 error (The page you're looking for can't be found.).
I guess the correct link is https://dcos.io/docs/1.7/usage/

**Comment by karlkfi** [comment]
Not sure what you mean... 
The link to https://dcos.io/docs/latest/usage/ is redirected to https://dcos.io/docs/1.7/usage/
Are you looking at docs for an old version of dcos-vagrant?

**Comment by fabriziopandini** [comment]
yep.
Checked again and now it works. Thanks for support
