### ISSUE TITLE
cant vagrant up a4

### ISSUE THREAD

**Issue by chshawkn** [dcos/dcos-vagrant#66]
repo is on master branch

DCOS1.7
dcos-vagrant box 0.6.3

MacBookPro 15inch with 16GB memory
OSX 10.11.5
vagrant 1.8.1
virtualbox 5.0.20

m1 a1 p1 boot is ok
then vagrant up a2 a3 a4
a2 a3 is ok, but a4 failed.

Same error multiple times.

console output:
......
==> a4: Checking Docker is configured with a production storage driver:
==> a4: WARNING: bridge-nf-call-iptables is disabled
==> a4: WARNING: bridge-nf-call-ip6tables is disabled
==> a4: PASS (overlay)
==> a4: Creating directories under /etc/mesosphere
==> a4: Creating role file for slave
==> a4: Configuring DC/OS
==> a4: Setting and starting DC/OS
==> a4: Created symlink from /etc/systemd/system/multi-user.target.wants/dcos-setup.service to /etc/systemd/system/dcos-setup.service.
==> a4: >>> Executing DC/OS Postflight
==> a4: /tmp/vagrant-shell: line 18: DCOS_TASK_MEMORY: unbound variable
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by chshawkn** [comment]
at https://github.com/dcos/dcos-vagrant/blob/master/VagrantConfig.yaml.example : 38
missing line
memory-reserved: 512

**Comment by karlkfi** [comment]
good catch. it should still work, but it seems the if statement here isn't doing what I expect: 
https://github.com/dcos/dcos-vagrant/blob/master/Vagrantfile#L85

**Comment by karlkfi** [comment]
Ah, never mind. That ruby is correct. The problem is in bash. There's an if statement for DCOS_TASK_MEMORY but it fails due to nounset.
https://github.com/dcos/dcos-vagrant/blob/master/provision/bin/type-agent-private.sh#L18

**Comment by karlkfi** [comment]
And of course, this code is only triggered when you add nodes to an existing cluster and you only get to a4 if you have a lot of ram available on your host! 

Fixed: https://github.com/dcos/dcos-vagrant/commit/f15ec906ecf7fa7b03fe00aabed1616fb608107e

**Comment by chshawkn** [comment]
Thank you for the details! This project is very helpful.
