### ISSUE TITLE
Having issues as #58

### ISSUE THREAD

**Issue by thbeh** [dcos/dcos-vagrant#74]
Hi,

I did a new clone and current vagrant box is 
mesosphere/dcos-centos-virtualbox           (virtualbox, 0.6.3)

after vagrant  up a1 m1 boot, all successful but cannot login with github.

Please advice.

**Comment by karlkfi** [comment]
Duplicate of JIRA ticket. Closing this one. https://dcosjira.atlassian.net/browse/VAGRANT-19
